name: Bun CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.1
      - run: bun install
      - run: bun run build

      - name: Create coverage
        run: ./scripts/coverage-badge.sh
      - name: Upload coverage.svg
        uses: actions/upload-artifact@v4
        with:
          name: "coverage.svg"
          path: ./coverage.svg
