name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          registry-url: "https://registry.npmjs.org"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.2.1
      - run: bun install
      - run: bun run build

      - name: Create coverage
        run: ./scripts/coverage-badge.sh
      - name: Upload coverage.svg
        uses: actions/upload-artifact@v4
        with:
          name: "coverage.svg"
          path: ./coverage.svg

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "coverage.svg"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
